### PR TITLE
Test requesting the same property twice

### PR DESCRIPTION
**Pull request by josephmturner**
Working on tracking down the bug in #6.  This test passes on my machine.

### CODE REVIEW

**Comment by josephmturner** [comment]
This last commit uses the real `hyper-sdk` in the test, and the second test hangs (as described in #6).

**Comment by josephmturner** [comment]
I tried to setting [tape's `opts.timeOut` flag](https://github.com/ljharb/tape#testname-opts-cb), but the terminal is still nonresponsive after the test times out.  What's a good way to stop the code that's running inside of a failed test with tape?

**Comment by RangerMauve** [comment]
after properly closing the sdk instance it's no longer hanging.

Diff I added:

```
diff --git a/test.js b/test.js
index 97b4565..0cba291 100644
--- a/test.js
+++ b/test.js
@@ -93,14 +93,18 @@ test('Request the same property twice', async function (t) {
     storage: false
   })
 
-  const client = new ClientConnection(clientConnection)
-  const server = new ServerConnection(sdk, serverConnection)
+  try {
+    const client = new ClientConnection(clientConnection)
+    const server = new ServerConnection(sdk, serverConnection)
 
-  client.process().catch((e) => t.fail(e))
-  server.process().catch((e) => t.fail(e))
+    client.process().catch((e) => t.fail(e))
+    server.process().catch((e) => t.fail(e))
 
-  const version = await client.call('sdk.getDrive(url).version', { 'url': KEY_NAME})
-  t.equal(version, 1, 'Got expected result from property')
-  const version2 = await client.call('sdk.getDrive(url).version', { 'url': KEY_NAME})
-  t.equal(version2, 1, 'Got expected result from property')
+    const version = await client.call('sdk.getDrive(url).version', { url: KEY_NAME })
+    t.equal(version, 1, 'Got expected result from property')
+    const version2 = await client.call('sdk.getDrive(url).version', { url: KEY_NAME })
+    t.equal(version2, 1, 'Got expected result from property')
+  } finally {
+    await sdk.close()
+  }
 })
```

**Comment by josephmturner** [comment]
I pushed your diff to the same `same-request-twice-hangs` branch, and it doesn't appear to solve the problem.  On my machine, the final `Request the same property twice` test prints:

```
# Request the same property twice
ok 10 Got expected result from property
```

and then hangs.  Are you able to reproduce this?

**Comment by josephmturner** [comment]
With https://github.com/RangerMauve/hyper-sdk-rpc/pull/12#issuecomment-1876145625, this issue is now resolved!

**Pull request closed without merging**
